EXE=jacobi

$(EXE): jacobi.c
	gcc -g -O3 -L/home/hankhoffmann/heartbeats-development/heartbeats-google-code/heartbeats/lib -I/home/hankhoffmann/heartbeats-development/heartbeats-google-code/heartbeats/inc/ jacobi.c -o jacobi -lhb-acc-pow-shared -lm -lrt -fopenmp

